name: calendrier
description: Une app Flutter pour survivre et autonomie
publish_to: "none" # Empêche la publication sur pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

# === Dépendances principales ===
dependencies:
  flutter:
    sdk: flutter


  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.2.1

# === Dépendances de développement ===
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.0

# === Configuration Flutter ===
flutter:
  uses-material-design: true

  # Tu peux ajouter tes assets/images ici si tu en as
  # assets:
  #   - assets/images/